// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package retrosheet

import (
	"database/sql"

	"github.com/google/uuid"
)

type RsBallpark struct {
	ID        string
	Name      string
	Nickname  sql.NullString
	City      sql.NullString
	State     sql.NullString
	StartDate sql.NullTime
	EndDate   sql.NullTime
	LeagueID  sql.NullString
}

type RsGameEvent struct {
	ID                   string
	GameID               string
	InnCt                int16
	OutsCt               int16
	BallsCt              int16
	StrikesCt            int16
	AwayScoreCt          int16
	HomeScoreCt          int16
	EventTx              sql.NullString
	LeadoffFl            bool
	PhFl                 bool
	BatFldCd             int16
	BatLineupSpot        int16
	BatEventFl           bool
	HCd                  sql.NullInt16
	ShFl                 bool
	SfFl                 bool
	EventOutsCt          int16
	DpFl                 bool
	TpFl                 bool
	RbiCt                int16
	WpFl                 bool
	PbFl                 bool
	FldCd                sql.NullInt16
	BattedballCd         sql.NullString
	BuntFl               bool
	FoulFl               bool
	BattedballLocTx      sql.NullString
	ErrCt                int16
	ErrFldCds            []string
	ErrCds               []string
	BatDestLoc           int16
	Run1DestLoc          int16
	Run2DestLoc          int16
	Run3DestLoc          int16
	BatPlayTx            sql.NullString
	Run1PlayTx           sql.NullString
	Run2PlayTx           sql.NullString
	Run3PlayTx           sql.NullString
	Run1SbFl             bool
	Run2SbFl             bool
	Run3SbFl             bool
	Run1CsFl             bool
	Run2CsFl             bool
	Run3CsFl             bool
	Run1PkFl             bool
	Run2PkFl             bool
	Run3PkFl             bool
	GameNewFl            bool
	GameEndFl            bool
	PrRun1Fl             bool
	PrRun2Fl             bool
	PrRun3Fl             bool
	RemovedForPhBatFldCd sql.NullInt16
	PoFldCds             []int16
	AssFldCds            []int16
	AwayTeamID           sql.NullString
	Base1RunID           sql.NullString
	Base2RunID           sql.NullString
	Base3RunID           sql.NullString
	BatTeamID            sql.NullString
	BatID                sql.NullString
	HomeTeamID           sql.NullString
	PitID                sql.NullString
	Pos2FldID            sql.NullString
	Pos3FldID            sql.NullString
	Pos4FldID            sql.NullString
	Pos5FldID            sql.NullString
	Pos6FldID            sql.NullString
	Pos7FldID            sql.NullString
	Pos8FldID            sql.NullString
	Pos9FldID            sql.NullString
	RemovedForPhBatID    sql.NullString
	RemovedForPrRun1ID   sql.NullString
	RemovedForPrRun2ID   sql.NullString
	RemovedForPrRun3ID   sql.NullString
	Run1RespPitID        sql.NullString
	Run2RespPitID        sql.NullString
	Run3RespPitID        sql.NullString
	Year                 int16
	Day                  int16
	Month                int16
}

type RsPlayer struct {
	ID           string
	LastName     string
	FirstName    string
	Nickname     sql.NullString
	Birthdate    sql.NullTime
	DebutDate    sql.NullTime
	LastGameDate sql.NullTime
}

type RsRoster struct {
	ID        uuid.UUID
	Year      int16
	TeamID    sql.NullString
	PlayerID  sql.NullString
	BatHand   string
	Position  string
	ThrowHand string
}

type RsTeam struct {
	ID        string
	LeagueID  sql.NullString
	City      string
	Nickname  string
	EndYear   int16
	StartYear int16
}
