-- l_batting: Lahman single season batting statistics
CREATE TABLE l_batting
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    year smallint NOT NULL,
    league character varying(2),
    g_cnt smallint,
    ab_cnt smallint,
    r_cnt smallint,
    h_cnt smallint,
    double_cnt smallint,
    triple_cnt smallint,
    hr_cnt smallint,
    rbi_cnt smallint,
    sb_cnt smallint,
    cs_cnt smallint,
    bb_cnt smallint,
    so_cnt smallint,
    ibb_cnt smallint,
    sf_cnt smallint,
    sh_cnt smallint,
    gidp_cnt smallint,
    player character varying(10) NOT NULL,
    team integer NOT NULL,
    CONSTRAINT l_batting_pkey PRIMARY KEY (id),
    CONSTRAINT l_batting_player_8dd5af7a_fk_l_player_id FOREIGN KEY (player)
        REFERENCES public.l_player (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT l_batting_team_b57b08b1_fk_l_team_id FOREIGN KEY (team)
        REFERENCES public.l_team (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

-- l_franchise: Lahman franchise entities
CREATE TABLE l_franchise
(
    id character varying(3) COLLATE pg_catalog."default" NOT NULL,
    name character varying(64) COLLATE pg_catalog."default",
    active boolean NOT NULL,
    CONSTRAINT l_franchise_pkey PRIMARY KEY (id)
);

-- l_pitching: Lahman single season pitching statistics
CREATE TABLE l_pitching
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    year smallint NOT NULL,
    league character varying(2) COLLATE pg_catalog."default",
    w_cnt smallint,
    l_cnt smallint,
    g_cnt smallint,
    gs_cnt smallint,
    cg_cnt smallint,
    sho_cnt smallint,
    sv_cnt smallint,
    ip_cnt smallint,
    h_cnt smallint,
    er_cnt smallint,
    hr_cnt smallint,
    bb_cnt smallint,
    so_cnt smallint,
    ba_opp double precision,
    era double precision,
    ibb_cnt smallint,
    wp_cnt smallint,
    hbp_cnt smallint,
    bk_cnt smallint,
    bfp_cnt smallint,
    gf_cnt smallint,
    r_cnt smallint,
    sh_cnt smallint,
    sf_cnt smallint,
    gidp_cnt smallint,
    player character varying(10) COLLATE pg_catalog."default" NOT NULL,
    team integer NOT NULL,
    CONSTRAINT l_pitching_pkey PRIMARY KEY (id),
    CONSTRAINT l_pitching_player_49772fae_fk_l_player_id FOREIGN KEY (player)
        REFERENCES public.l_player (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT l_pitching_team_43f50601_fk_l_team_id FOREIGN KEY (team)
        REFERENCES public.l_team (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

-- l_player: Lahman player entities
CREATE TABLE l_player
(
    id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    given_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    birth_year smallint,
    birth_month smallint,
    birth_day smallint,
    birth_country character varying(64) COLLATE pg_catalog."default",
    birth_state character varying(64) COLLATE pg_catalog."default",
    birth_city character varying(64) COLLATE pg_catalog."default",
    death_year smallint,
    death_month smallint,
    death_day smallint,
    death_country character varying(64) COLLATE pg_catalog."default",
    death_state character varying(64) COLLATE pg_catalog."default",
    death_city character varying(64) COLLATE pg_catalog."default",
    height double precision,
    weight double precision,
    bat_hand character varying(2) COLLATE pg_catalog."default" NOT NULL,
    throw_hand character varying(2) COLLATE pg_catalog."default" NOT NULL,
    debut_date date,
    final_game_date date,
    bbref character varying(10) COLLATE pg_catalog."default",
    retrosheet character varying(8) COLLATE pg_catalog."default",
    CONSTRAINT l_player_pkey PRIMARY KEY (id),
    CONSTRAINT l_player_retrosheet_af867963_fk_rs_player_id FOREIGN KEY (retrosheet)
        REFERENCES public.rs_player (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

-- l_team: Lahman team entities
CREATE TABLE l_team
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    year smallint,
    team character varying(3) COLLATE pg_catalog."default" NOT NULL,
    league character varying(2) COLLATE pg_catalog."default",
    division character varying(1) COLLATE pg_catalog."default",
    rank smallint,
    game_cnt smallint,
    home_game_cnt smallint,
    w_cnt smallint,
    l_cnt smallint,
    ds_win boolean,
    wc_win boolean,
    lg_win boolean,
    ws_win boolean,
    r_cnt smallint,
    ab_cnt smallint,
    h_cnt smallint,
    double_cnt smallint,
    triple_cnt smallint,
    hr_cnt smallint,
    bb_cnt smallint,
    so_cnt smallint,
    sb_cnt smallint,
    cs_cnt smallint,
    hbp_cnt smallint,
    sf_cnt smallint,
    ra_cnt smallint,
    er_cnt smallint,
    era double precision,
    cg_cnt smallint,
    sho_cnt smallint,
    sv_cnt smallint,
    ip_cnt smallint,
    ha_cnt smallint,
    hra_cnt smallint,
    bba_cnt smallint,
    soa_cnt smallint,
    e_cnt smallint,
    franchise character varying(3) COLLATE pg_catalog."default",
    CONSTRAINT l_team_pkey PRIMARY KEY (id),
    CONSTRAINT l_team_team_year_ad9bb185_uniq UNIQUE (team, year),
    CONSTRAINT l_team_franchise_ac81a53b_fk FOREIGN KEY (franchise)
        REFERENCES public.l_franchise (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT l_team_rank_check CHECK (rank >= 0)
);
